modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ecarrascon/carrasconlib/issues"
license = "MIT"

[[mods]]
modId = "carrasconlib"
version = "${version}"
displayName = "Carrascon Lib"
authors = "ECarrascon"
description = '''
A library for ECarrascon Mods
'''
logoFile = "icon.png"

[[dependencies.carrasconlib]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.carrasconlib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.carrasconlib]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "carrasconlib.mixins.json"
